apiVersion: 1


datasources:
  - name: Postgres
    uid: hn_postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    isDefault: true
    editable: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
